<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between"><h2 class="text-xl font-bold text-gray-800">Panel de administración</h2><a href="{{ route('dashboard') }}" class="rounded border px-3 py-2 text-xs">Tablero</a></div>
    </x-slot>
    <div class="min-h-screen bg-gray-50 p-5">
        <div class="mx-auto max-w-6xl space-y-5">
            @if(session('success'))<div class="rounded bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
            <section class="rounded-xl bg-white p-5 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs uppercase tracking-widest text-pink-500">Empresa activa</p><h1 class="text-xl font-bold">{{ $company->name }}</h1><p class="text-sm text-gray-500">{{ $company->tax_id ?: 'Sin NIT configurado' }}</p></div><a href="{{ route('third-parties.index') }}" class="rounded bg-pink-600 px-3 py-2 text-xs font-bold text-white">Gestionar terceros</a></div></section>
            <div class="grid gap-5 lg:grid-cols-2">
                <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="mb-4 font-bold">Crear empresa</h2><form method="POST" action="{{ route('admin.companies.store') }}" class="space-y-3">@csrf<input name="name" required placeholder="Razón social" class="w-full rounded border-gray-300 text-sm"><input name="tax_id" placeholder="NIT" class="w-full rounded border-gray-300 text-sm"><input name="email" type="email" placeholder="Correo" class="w-full rounded border-gray-300 text-sm"><button class="rounded bg-pink-600 px-3 py-2 text-sm font-bold text-white">Crear y asociar</button></form><h2 class="mb-3 mt-6 font-bold">Mis empresas</h2>@foreach($companies as $item)<div class="flex justify-between border-b py-2 text-sm"><span>{{ $item->name }}</span><span class="text-gray-500">{{ $item->users_count }} usuarios</span></div>@endforeach</section>
                <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="mb-4 font-bold">Usuarios y roles</h2><form method="POST" action="{{ route('admin.members.store') }}" class="mb-5 flex flex-wrap gap-2">@csrf<input name="email" type="email" required placeholder="Correo de usuario existente" class="flex-1 rounded border-gray-300 text-sm"><select name="role" class="rounded border-gray-300 text-sm"><option value="contador">Contador</option><option value="auxiliar">Auxiliar</option><option value="vendedor">Vendedor</option><option value="consulta">Consulta</option><option value="admin">Administrador</option></select><button class="rounded bg-gray-800 px-3 py-2 text-xs font-bold text-white">Agregar</button></form><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b text-xs uppercase"><tr><th class="p-2">Usuario</th><th class="p-2">Correo</th><th class="p-2">Rol</th></tr></thead><tbody>@foreach($members as $member)<tr class="border-b"><td class="p-2">{{ $member->name }}</td><td class="p-2">{{ $member->email }}</td><td class="p-2"><form method="POST" action="{{ route('admin.members.role', $member) }}" class="flex gap-1">@csrf @method('PUT')<select name="role" class="rounded border-gray-300 text-xs"><option value="admin" @selected($member->pivot->role === 'admin')>Admin</option><option value="contador" @selected($member->pivot->role === 'contador')>Contador</option><option value="auxiliar" @selected($member->pivot->role === 'auxiliar')>Auxiliar</option><option value="vendedor" @selected($member->pivot->role === 'vendedor')>Vendedor</option><option value="consulta" @selected($member->pivot->role === 'consulta')>Consulta</option></select><button class="text-pink-600">Guardar</button></form></td></tr>@endforeach</tbody></table></div></section>
            </div>
            <section class="rounded-xl bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs uppercase tracking-widest text-pink-500">Configuración contable</p><h2 class="mt-1 text-lg font-bold">Formas de pago y cuenta PUC</h2><p class="mt-1 text-sm text-gray-500">Crea las formas de pago que necesites (efectivo, bancos, proveedores, etc.) y asocia cada una con su cuenta auxiliar.</p></div><div class="flex gap-2"><form method="POST" action="{{ route('admin.puc.seed') }}" onsubmit="return confirm('Esto crea las cuentas PUC estándar que falten para esta empresa, sin tocar las que ya existen. ¿Continuar?')">@csrf<button class="rounded border px-3 py-2 text-xs font-bold text-gray-700">Restaurar catálogo estándar</button></form><a href="{{ route('accounting.puc.index') }}" class="rounded border px-3 py-2 text-xs font-bold text-gray-700">Administrar PUC</a></div></div>
                <form method="POST" action="{{ route('admin.payment-methods.store') }}" class="mt-4 flex flex-wrap items-end gap-2 rounded-lg border border-gray-200 bg-gray-50 p-3">
                    @csrf
                    <div class="flex-1"><label class="mb-1 block text-xs font-bold text-gray-500">Nueva forma de pago</label><input name="name" required placeholder="Ej. Transferencia proveedor, Nequi, Daviplata..." class="w-full rounded border-gray-300 text-sm"></div>
                    <div class="flex-1"><label class="mb-1 block text-xs font-bold text-gray-500">Banco (opcional)</label><input name="bank_name" placeholder="Ej. Bancolombia" class="w-full rounded border-gray-300 text-sm"></div>
                    <div class="flex-1"><label class="mb-1 block text-xs font-bold text-gray-500">N° de cuenta (opcional)</label><input name="account_number" placeholder="Ej. 1020459855" class="w-full rounded border-gray-300 text-sm"></div>
                    <div class="flex-1"><label class="mb-1 block text-xs font-bold text-gray-500">Cuenta PUC (opcional)</label><select name="chart_of_account_id" class="w-full rounded border-gray-300 text-sm"><option value="">Sin asociación</option>@foreach($postingAccounts as $account)<option value="{{ $account->id }}">{{ $account->code }} - {{ $account->name }}</option>@endforeach</select></div>
                    <label class="flex items-center gap-1 text-xs font-bold text-gray-500"><input type="checkbox" name="is_cash" value="1"> Es caja (efectivo)</label>
                    <button class="rounded bg-pink-600 px-3 py-2 text-xs font-bold text-white">+ Crear forma de pago</button>
                </form>
                <div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b bg-gray-50 text-xs uppercase"><tr><th class="p-2">Forma de pago</th><th class="p-2">Banco / N° cuenta / Cuenta PUC</th><th class="p-2">Acción</th></tr></thead><tbody>@forelse($paymentMethods as $paymentMethod)<tr class="border-b"><td class="p-2 font-semibold align-top">{{ $paymentMethod->name }}{{ $paymentMethod->is_cash ? ' (Caja)' : '' }}</td><td class="p-2"><form method="POST" action="{{ route('admin.payment-methods.puc', $paymentMethod) }}" class="flex flex-wrap items-center gap-2">@csrf @method('PUT')<input name="bank_name" value="{{ $paymentMethod->bank_name }}" placeholder="Banco" class="w-28 rounded border-gray-300 text-xs"><input name="account_number" value="{{ $paymentMethod->account_number }}" placeholder="N° cuenta" class="w-28 rounded border-gray-300 text-xs"><select name="chart_of_account_id" class="rounded border-gray-300 text-sm"><option value="">Sin asociación</option>@foreach($postingAccounts as $account)<option value="{{ $account->id }}" @selected($paymentMethod->chart_of_account_id === $account->id)>{{ $account->code }} - {{ $account->name }}</option>@endforeach</select><label class="inline-flex items-center gap-1 text-xs"><input type="checkbox" name="is_cash" value="1" @checked($paymentMethod->is_cash)> Caja</label><button class="rounded bg-[#227c70] px-3 py-2 text-xs font-bold text-white">Guardar</button></form></td><td class="p-2"><form method="POST" action="{{ route('admin.payment-methods.destroy', $paymentMethod) }}" onsubmit="return confirm('¿Eliminar esta forma de pago?')">@csrf @method('DELETE')<button class="rounded border border-red-200 px-3 py-2 text-xs font-bold text-red-600">Eliminar</button></form></td></tr>@empty<tr><td colspan="3" class="p-3 text-sm text-gray-500">Aún no hay formas de pago configuradas.</td></tr>@endforelse</tbody></table></div></section>
            <section class="rounded-xl bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs uppercase tracking-widest text-pink-500">Facturación electrónica</p><h2 class="mt-1 text-lg font-bold">Credenciales de Factus</h2><p class="mt-1 text-sm text-gray-500">Regístrate en <a href="https://www.factus.com.co" target="_blank" class="text-pink-600 underline">factus.com.co</a> y pega aquí las credenciales que te asignen para esta empresa.</p></div></div><form method="POST" action="{{ route('admin.factus.update') }}" class="mt-4 grid gap-3 md:grid-cols-2">@csrf<select name="environment" class="rounded border-gray-300 text-sm"><option value="sandbox" @selected(($factusCredential->environment ?? 'sandbox') === 'sandbox')>Pruebas (sandbox)</option><option value="production" @selected(($factusCredential->environment ?? null) === 'production')>Producción</option></select><input name="invoice_numbering_range_id" type="number" value="{{ $factusCredential->invoice_numbering_range_id ?? '' }}" placeholder="ID de rango de numeración (facturas)" class="w-full rounded border-gray-300 text-sm"><input name="payroll_numbering_range_id" type="number" value="{{ $factusCredential->payroll_numbering_range_id ?? '' }}" placeholder="ID de rango de numeración (nómina)" class="w-full rounded border-gray-300 text-sm"><input name="client_id" required value="{{ $factusCredential->client_id ?? '' }}" placeholder="Client ID" class="w-full rounded border-gray-300 text-sm"><input name="client_secret" type="password" required placeholder="Client secret" class="w-full rounded border-gray-300 text-sm"><input name="username" required value="{{ $factusCredential->username ?? '' }}" placeholder="Correo de usuario Factus" class="w-full rounded border-gray-300 text-sm"><input name="password" type="password" required placeholder="Contraseña" class="w-full rounded border-gray-300 text-sm"><button class="rounded bg-pink-600 px-3 py-2 text-sm font-bold text-white md:col-span-2">Guardar credenciales</button></form>@if($factusCredential)<p class="mt-2 text-xs text-emerald-600">Credenciales configuradas ({{ $factusCredential->environment }}).</p>@endif</section>

            <section class="rounded-xl bg-white p-5 shadow-sm">
                <div class="flex flex-wrap items-start justify-between gap-3">
                    <div>
                        <p class="text-xs uppercase tracking-widest text-pink-500">Seguridad social</p>
                        <h2 class="mt-1 text-lg font-bold">Operador de planillas (PILA)</h2>
                        <p class="mt-1 text-sm text-gray-500">Configura el nombre y la URL de tu operador de PILA (por ejemplo, Enlace Operativo) para acceder a él con un clic desde Nómina y desde el comprobante de seguridad social.</p>
                    </div>
                </div>
                <form method="POST" action="{{ route('admin.social-security.update') }}" class="mt-4 grid gap-3 md:grid-cols-2">
                    @csrf
                    <input name="social_security_operator_name" value="{{ $company->social_security_operator_name ?? 'Enlace Operativo' }}" placeholder="Nombre del operador" class="w-full rounded border-gray-300 text-sm">
                    <input name="social_security_operator_url" type="url" value="{{ $company->social_security_operator_url ?? '' }}" placeholder="https://www.enlaceoperativo.com" class="w-full rounded border-gray-300 text-sm">
                    <button class="rounded bg-pink-600 px-3 py-2 text-sm font-bold text-white md:col-span-2">Guardar operador de PILA</button>
                </form>
                @if($company->social_security_operator_url)
                    <p class="mt-2 text-xs text-emerald-600">Configurado: {{ $company->social_security_operator_name }} ({{ $company->social_security_operator_url }}).</p>
                @endif
            </section>

            <section class="rounded-xl bg-white p-5 shadow-sm">
                <div class="flex flex-wrap items-start justify-between gap-3">
                    <div>
                        <p class="text-xs uppercase tracking-widest text-pink-500">Impuestos</p>
                        <h2 class="mt-1 text-lg font-bold">Tarifas para borradores de impuestos</h2>
                        <p class="mt-1 text-sm text-gray-500">Configura la tarifa de ICA de tu municipio (por mil) y la tarifa de renta aplicable para que el módulo de <a href="{{ route('tax-drafts.index') }}" class="text-pink-600 underline">Borradores de impuestos</a> calcule montos exactos.</p>
                    </div>
                </div>
                <form method="POST" action="{{ route('admin.tax-settings.update') }}" class="mt-4 grid gap-3 md:grid-cols-2">
                    @csrf
                    <input name="ica_rate_per_thousand" type="number" step="0.01" min="0" value="{{ $company->ica_rate_per_thousand ?? '' }}" placeholder="Tarifa ICA por mil (ej. 6.9)" class="w-full rounded border-gray-300 text-sm">
                    <input name="income_tax_rate_percentage" type="number" step="0.01" min="0" value="{{ $company->income_tax_rate_percentage ?? '' }}" placeholder="Tarifa de renta % (ej. 35)" class="w-full rounded border-gray-300 text-sm">
                    <button class="rounded bg-pink-600 px-3 py-2 text-sm font-bold text-white md:col-span-2">Guardar tarifas</button>
                </form>
            </section>
        </div>
    </div>
</x-app-layout>
