<x-app-layout>
    <x-slot name="header">
        <div class="flex items-center justify-between"><h2 class="text-xl font-bold text-gray-800">Panel de administración</h2><a href="{{ route('dashboard') }}" class="rounded border px-3 py-2 text-xs">Tablero</a></div>
    </x-slot>
    <div class="min-h-screen bg-gray-50 p-5">
        <div class="mx-auto max-w-6xl space-y-5">
            @if(session('success'))<div class="rounded bg-emerald-50 p-3 text-sm text-emerald-700">{{ session('success') }}</div>@endif
            <section class="rounded-xl bg-white p-5 shadow-sm"><div class="flex flex-wrap items-center justify-between gap-3"><div><p class="text-xs uppercase tracking-widest text-pink-500">Empresa activa</p><h1 class="text-xl font-bold">{{ $company->name }}</h1><p class="text-sm text-gray-500">{{ $company->tax_id ?: 'Sin NIT configurado' }}</p></div><a href="{{ route('third-parties.index') }}" class="rounded bg-pink-600 px-3 py-2 text-xs font-bold text-white">Gestionar terceros</a></div></section>
            <div class="grid gap-5 lg:grid-cols-2">
                <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="mb-4 font-bold">Crear empresa</h2><form method="POST" action="{{ route('admin.companies.store') }}" class="space-y-3">@csrf<input name="name" required placeholder="Razón social" class="w-full rounded border-gray-300 text-sm"><input name="tax_id" placeholder="NIT" class="w-full rounded border-gray-300 text-sm"><input name="email" type="email" placeholder="Correo" class="w-full rounded border-gray-300 text-sm"><button class="rounded bg-pink-600 px-3 py-2 text-sm font-bold text-white">Crear y asociar</button></form><h2 class="mb-3 mt-6 font-bold">Mis empresas</h2>@foreach($companies as $item)<div class="flex justify-between border-b py-2 text-sm"><span>{{ $item->name }}</span><span class="text-gray-500">{{ $item->users_count }} usuarios</span></div>@endforeach</section>
                <section class="rounded-xl bg-white p-5 shadow-sm"><h2 class="mb-4 font-bold">Usuarios y roles</h2><form method="POST" action="{{ route('admin.members.store') }}" class="mb-5 flex flex-wrap gap-2">@csrf<input name="email" type="email" required placeholder="Correo de usuario existente" class="flex-1 rounded border-gray-300 text-sm"><select name="role" class="rounded border-gray-300 text-sm"><option value="contador">Contador</option><option value="auxiliar">Auxiliar</option><option value="vendedor">Vendedor</option><option value="consulta">Consulta</option><option value="admin">Administrador</option></select><button class="rounded bg-gray-800 px-3 py-2 text-xs font-bold text-white">Agregar</button></form><div class="overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b text-xs uppercase"><tr><th class="p-2">Usuario</th><th class="p-2">Correo</th><th class="p-2">Rol</th></tr></thead><tbody>@foreach($members as $member)<tr class="border-b"><td class="p-2">{{ $member->name }}</td><td class="p-2">{{ $member->email }}</td><td class="p-2"><form method="POST" action="{{ route('admin.members.role', $member) }}" class="flex gap-1">@csrf @method('PUT')<select name="role" class="rounded border-gray-300 text-xs"><option value="admin" @selected($member->pivot->role === 'admin')>Admin</option><option value="contador" @selected($member->pivot->role === 'contador')>Contador</option><option value="auxiliar" @selected($member->pivot->role === 'auxiliar')>Auxiliar</option><option value="vendedor" @selected($member->pivot->role === 'vendedor')>Vendedor</option><option value="consulta" @selected($member->pivot->role === 'consulta')>Consulta</option></select><button class="text-pink-600">Guardar</button></form></td></tr>@endforeach</tbody></table></div></section>
            </div>
            <section class="rounded-xl bg-white p-5 shadow-sm"><div class="flex flex-wrap items-start justify-between gap-3"><div><p class="text-xs uppercase tracking-widest text-pink-500">Configuración contable</p><h2 class="mt-1 text-lg font-bold">Formas de pago y cuenta PUC</h2><p class="mt-1 text-sm text-gray-500">Asocia cada forma de pago con una cuenta auxiliar.</p></div><div class="flex gap-2"><form method="POST" action="{{ route('admin.puc.seed') }}" onsubmit="return confirm('Esto crea las cuentas PUC estándar que falten para esta empresa, sin tocar las que ya existen. ¿Continuar?')">@csrf<button class="rounded border px-3 py-2 text-xs font-bold text-gray-700">Restaurar catálogo estándar</button></form><a href="{{ route('accounting.puc.index') }}" class="rounded border px-3 py-2 text-xs font-bold text-gray-700">Administrar PUC</a></div></div><div class="mt-4 overflow-x-auto"><table class="w-full text-left text-sm"><thead class="border-b bg-gray-50 text-xs uppercase"><tr><th class="p-2">Forma de pago</th><th class="p-2">Cuenta PUC</th><th class="p-2">Acción</th></tr></thead><tbody>@forelse($paymentMethods as $paymentMethod)<tr class="border-b"><td class="p-2 font-semibold">{{ $paymentMethod->name }}</td><td class="p-2"><form method="POST" action="{{ route('admin.payment-methods.puc', $paymentMethod) }}" class="flex flex-wrap gap-2">@csrf @method('PUT')<select name="chart_of_account_id" class="rounded border-gray-300 text-sm"><option value="">Sin asociación</option>@foreach($postingAccounts as $account)<option value="{{ $account->id }}" @selected($paymentMethod->chart_of_account_id === $account->id)>{{ $account->code }} - {{ $account->name }}</option>@endforeach</select></td><td class="p-2"><button class="rounded bg-[#227c70] px-3 py-2 text-xs font-bold text-white">Guardar</button></form></td></tr>@empty<tr><td colspan="3" class="p-3 text-sm text-gray-500">Aún no hay formas de pago configuradas.</td></tr>@endforelse</tbody></table></div></section>
        </div>
    </div>
</x-app-layout>
